---
title: "Basic Analysis"
author: "Nhi Nguyen"
date: "2025-05-10"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load Libraries, message=FALSE}

library(readr)
library(tidyverse)

```

```{r Load in Data, message=FALSE}

data_train <- read_csv("training_set_features.csv")
data_train_labels <- read_csv("training_set_labels.csv")
data_test <- read_csv("test_set_features.csv")

```

```{r Get Overiew of Data}

head(data_train)
head(data_train_labels)
head(data_test)

str(data_train)
str(data_train_labels)
str(data_test)

summary(data_train)
summary(data_train_labels)
summary(data_test)

sum(is.na(data_train))
sum(is.na(data_train_labels))
sum(is.na(data_test))

```

```{r Adjust Data types and replace NA}

data_train <- data_train %>%
  mutate(across(where(is.character), ~ replace_na(.x, "Missing")),
         across(where(is.numeric), ~ replace_na(.x, -1)), # -1 meaning missing
         across(2:last_col(), factor))

sum(is.na(data_train))

data_train_labels <- data_train_labels %>% 
  mutate(across(2:last_col(), factor))

data_test <- data_test %>%
  mutate(across(where(is.character), ~ replace_na(.x, "Missing")),
         across(where(is.numeric), ~ replace_na(.x, -1)), # -1 meaning missing
         across(2:last_col(), factor))

sum(is.na(data_test))
```

```{r Frequency Table}

data_train <- data_train %>%
  full_join(data_train_labels, by = "respondent_id")

prop.table(data_train$h1n1_vaccine)
prop.table(data_train$seasonal_vaccine)

```



